_BASE_: ../Cityscapes-PanopticSegmentation/Base-PanopticDeepLab-OS16.yaml
MODEL:
  META_ARCHITECTURE: "PanopticSwiftNet"
#  WEIGHTS: "/home/jsaric/workspace/detectron2/projects/Panoptic-DeepLab/output/psn-18-coco-weights/model_final.pth"
#  PIXEL_MEAN: [123.675, 116.280, 103.530]
#  PIXEL_STD: [58.395, 57.120, 57.375]
  PIXEL_MEAN: (0.485, 0.456, 0.406)
  PIXEL_STD: (0.229, 0.224, 0.225)
  BACKBONE:
    NAME: "resnet"
  RESNETS:
    DEPTH: 18
  PANOPTIC_SWIFTNET:
    STUFF_AREA: 2048
    NMS_KERNEL: 7
    SIZE_DIVISIBILITY: 128
    NUM_CLASSES: 19
    SYNCBN: True
    FINAL_UP_ALIGN_CORNERS: True
    SEMANTIC_LOSS:
      TYPE: "hard_pixel_mining"
      LOSS_TOP_K: 0.2
    INSTANCE_LOSS:
      CENTER_LOSS_WEIGHT: 200.0
      OFFSET_LOSS_WEIGHT: 0.0025
      BAOL:
        ENABLED: True
        WEIGHTS_PATH: "/home/shared/datasets/cityscapes/gtFine/panoptic_train-offset_weightsSR_8_0_4_0_2_0_1_0"
    DECODER:
      TYPE: "SHARED"
  PANOPTIC_DEEPLAB:
    STUFF_AREA: 2048
    NMS_KERNEL: 7
    SIZE_DIVISIBILITY: 128
    PREDICT_INSTANCES: False
DATASETS:
  TRAIN: ("cityscapes_fine_panoptic_train",)
  TEST: ("cityscapes_fine_panoptic_val",)
#DATALOADER:
#  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
#  REPEAT_THRESHOLD: 0.1
SOLVER:
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  POLY_LR_POWER: 0.9
  POLY_LR_CONSTANT_ENDING: 0.0
  OPTIMIZER: "ADAM"
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  WARMUP_ITERS: 0
  BASE_LR: 0.0001
  MAX_ITER: 90000
  IMS_PER_BATCH: 8
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (512, 640, 704, 832, 896, 1024, 1152, 1216, 1344, 1408, 1536)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  FORMAT: "RGB"
  CLASS_BALANCED_CROPS: False
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (1024, 2048)
OUTPUT_DIR: "./output/r18-d256-cityscapes-baol/"